### ISSUE TITLE
Skok prilikom promene platforme

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG004-izbegni-ambis#2]
Probajte da sredite naglu promenu poziciju kockice prilikom promene pravca kretanja

**Comment by lukamilosevic11** [comment]
Mislim da je sada bolji prelazak,
stavio sam if u kom se gleda u kom smeru ce kockica da se krece
pre naredbe gde se ta kockica pomera i onda se prvo odredi pravi smer kockice i tek onda se ona pomera.
Do sada je taj if bio posle toga pa je kockica taj prvi prelazak mogla da ide u pogresnom smeru ako je tako sacuvano u proslom pomeranju kockice.
