### ISSUE TITLE
Pregledanje rada za JAN2

### ISSUE THREAD

**Issue by lukamilosevic11** [MATF-RG17/RG004-izbegni-ambis#3]
Promenjeno u odnosu na pregledanje rada u JAN1:
rasporedjeno u vise fajlova 
poboljsan prelazak sa jednog objekta na drugi
dodato ubrzanje kockice posle nekoliko uspesnih prelaska
dodato menjanje boje svih objekata nasumicnim bojama da bi se dodatno otezalo igranje kada brzina kocke predje 0.5

**Comment by ivan-cukic-matf** [comment]
Dodajte izveštaj (ovo iznad što se napisali), napravite još nekoliko izmena, dodajte izveštaj o tome i otvorite ovaj issue opet. Izveštaji nose ukupno 4 poena, bilo bi dobro da ih ne izgubite sve bez razloga.
